### ISSUE TITLE
this.xThumb is null 

### ISSUE THREAD

**Issue by HC-Team** [dwqs/v2-table#1]
Hey thanks for that nice component, I have an issue when I try to destroy that component (route change) it always throws that error:

`this.xThumb is null `

Any idea?

**Comment by dwqs** [comment]
Can you show me the code and the in detail error info?

**Comment by dwqs** [comment]
Maybe I know the reason, I will fix it as soon as possible.

**Comment by HC-Team** [comment]
Works, THX!
