### ISSUE TITLE
Refreshing data in table + add icon to call method

### ISSUE THREAD

**Issue by bbogda** [dwqs/v2-table#13]
I think about opportunity refresh my data.
How to call method on demand
```
fetchData() {
      this.$http.get('v_sim.php').then(response => {
        this.list = response.body 
      }, response => { return 'error' })
    }
```
Maybe some simple solutions e.g. some icon similar to sortable in first header column?
Or maybe is something similar in library?

Thanks for v2-table :+1: 

And for QuickStart & Example give :100:

**Comment by dwqs** [comment]
call method on demand？？？more details?

**Comment by bbogda** [comment]
Something similar to :
@sort-change="handleSortChange" - when click icon of 'sorting' then method handleSortChange() does it.
`  <v2-table :data="list" @sort-change="handleSortChange" >`
e.g. @refresh-data="fetchData" - push icon of 'refresh' to get data and display to table.

**Comment by dwqs** [comment]
```
<template>
// Maybe you should put a button or a refresh icon to trigger fetchData outside the table
<button @click="fetchData">refresh</button>
<v2-table :data="list" @sort-change="handleSortChange">
<v2-table-column label="Rej" prop="rej" sortable ></v2-table-column>
 ...
</template>
```

I have no idea to put refresh icon inside v2-table. The data maybe can sort, so header columns should put sorting icon.

**Comment by bbogda** [comment]
Yeah I was thinking about it.
It's not so elegant solution.
And have problem with call method via 'dashboard-container' where table is one of piece panel-group element.
But many thanks for reply.
