### ISSUE TITLE
TypeError: i.a is not a constructor

### ISSUE THREAD

**Issue by kevinding0218** [dwqs/v2-table#5]
Hello,

   Your v2-table is really awesome! But I am getting an error while trying to use it in a single html page design, could you please provide me some suggestions? This is what I did:
<script src="vue.js"></script>
<script src="v2-table/v2-table.js"></script>

Vue.use(V2Table);
[Vue warn]: Error in nextTick: "TypeError: i.a is not a constructor"

found in

---> <V2Table> at src/components/table.vue
       <Root>

Best,

**Comment by dwqs** [comment]
which version you used?

**Comment by kevinding0218** [comment]
Excellent Catch! My bad I did not noticed that, thank you very much for your help!

Best,
