### ISSUE TITLE
Is there a way to set specific rows to be checked?

### ISSUE THREAD

**Issue by kevinding0218** [dwqs/v2-table#6]
Hello I've been using the v2-table for some design purpose but I could not figure out a way to bind the checked attribute of column with type "selection", so I cannot set some rows to be selected programmably, I've tried using "prop" attribute but it won't work...
e.g:
<v2-table-column type="selection" width="45" prop="checked"></v2-table-column>
data: [{checked: true, name: 'jason', state:'CA'}, {checked: false, name: 'mike', state:'CA'}, {checked: true, name: 'Lu', state:'CA'},...]
Do you have any example upon this functionality? 

Thank you very much for your help!

Best,

**Comment by dwqs** [comment]
Not supports this feature......I will implement it as soon as possible

**Comment by dwqs** [comment]
Upgrade to 1.2.2, and call `toggleRowSelection` to change the row selection status.

```js
<v2-table ref="table" :data="rows">
 // ...
</v2-table>


 this.$refs.table.toggleRowSelection(this.rows[0], [selected])   // selected is optional
```
